# Generated by Django 5.2.8 on 2026-01-08 11:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xizmat_hujjatlari', models.FileField(upload_to='hujjatlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppr_qilish_oylik', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObyektNomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obyekt_nomi', models.CharField(max_length=255)),
                ('toliq_nomi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PPRYakunlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakunlash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('monitoring', 'Monitoring'), ('tarkibiy', 'Tarkibiy Tuzilma Rahbari'), ('bekat', 'Bekat Rahbari'), ('bolim', "Bo'lim Boshlig'i")], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_seriya', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArizaYuborish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('ijro', 'Ijro uchun'), ('malumot', "Ma'lumot uchun")], default='ijro', max_length=15)),
                ('ijro_muddati', models.DateField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('parol', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi'), ('qabul qilindi', 'Qabul qilindi'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('bildirgi', models.FileField(blank=True, null=True, upload_to='ariza_bildirgilar/')),
                ('qayta_yuklandi', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kim_tomonidan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ariza_kim', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
            ],
        ),
        migrations.CreateModel(
            name='ArizaYuborishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='ariza_rasmlar_multi/')),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='ppr.arizayuborish')),
            ],
        ),
        migrations.CreateModel(
            name='Bekat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bekat_nomi', models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Mingoʻrik', 'Mingoʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Sergeli', 'Sergeli'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Paxtakor', 'Paxtakor'), ('Qipchoq', 'Qipchoq'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=255)),
                ('faoliyati', models.TextField()),
                ('rahbari', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_seriya', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField()),
                ('is_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bekat_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bekat_pending_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bekat_nomi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ppr.bekat'),
        ),
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(max_length=255)),
                ('faoliyati', models.TextField()),
                ('rahbari', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bolim_photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_seriya', models.CharField(blank=True, max_length=9, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolim_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolim_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ppr.bolim'),
        ),
        migrations.CreateModel(
            name='KelganArizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilovalar', models.FileField(blank=True, null=True, upload_to='ilovalar/')),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='kelgan_fayllar/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('parol', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('turi', models.CharField(max_length=50)),
                ('ijro_muddati', models.DateField(blank=True, null=True)),
                ('bildirgi', models.FileField(blank=True, null=True, upload_to='ariza_bildirgilar/')),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelganlar', to='ppr.arizayuborish')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KelganArizaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='ariza_rasmlar_multi/')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='ppr.kelganarizalar')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faoliyati', models.TextField()),
                ('rahbari', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='monitoring_photos/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_seriya', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='monitoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ppr.monitoring'),
        ),
        migrations.CreateModel(
            name='ObyektLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obyekt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='ppr.obyektnomi')),
            ],
        ),
        migrations.CreateModel(
            name='PPRJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy', models.CharField(blank=True, choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=20, null=True)),
                ('boshlash_sanasi', models.DateField(blank=True, null=True)),
                ('yakunlash_sanasi', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('obyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.obyektnomi')),
            ],
        ),
        migrations.CreateModel(
            name='PPRBajarildi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ppr_bajarildi_files/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ppr_bajarildi_images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jadval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajarildi', to='ppr.pprjadval')),
            ],
        ),
        migrations.CreateModel(
            name='PPRTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, help_text='Masalan: Nomi', max_length=100, null=True)),
                ('qisqachanomi', models.CharField(blank=True, help_text='Masalan: Qisqa nomi', max_length=100, null=True)),
                ('davriyligi', models.IntegerField(blank=True, help_text='Masalan: qancha vaqtda', max_length=100, null=True)),
                ('vaqti', models.CharField(blank=True, choices=[('soat', 'soat'), ('kun', 'kun'), ('oy', 'oy')], max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ppr_turlari/')),
                ('kimlar_qiladi', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='ppr_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.pprturi'),
        ),
        migrations.CreateModel(
            name='TarkibiyTuzilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuzilma_nomi', models.CharField(max_length=255)),
                ('faoliyati', models.TextField()),
                ('rahbari', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_seriya', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField()),
                ('is_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuzilma_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuzilma_pending_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bolim',
            name='tuzilma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolimlar', to='ppr.tarkibiytuzilma'),
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='tuzilmalar',
            field=models.ManyToManyField(related_name='arizalar', to='ppr.tarkibiytuzilma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tarkibiy_tuzilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ppr.tarkibiytuzilma'),
        ),
    ]
