# Generated by Django 5.2.8 on 2025-12-25 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPRYakunlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakunlash', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='pprjadval',
            old_name='sana',
            new_name='boshlash_sanasi',
        ),
        migrations.RemoveField(
            model_name='pprjadval',
            name='kim_tomonidan',
        ),
        migrations.AddField(
            model_name='obyektnomi',
            name='toliq_nomi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='yakunlash_sanasi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pprjadval',
            name='oy',
            field=models.CharField(blank=True, choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ObyektLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obyekt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='ppr.obyektnomi')),
            ],
        ),
    ]
