# Generated by Django 5.2.8 on 2026-02-23 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tuzilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolim_kategoriyalari', to='ppr.tarkibiytuzilma')),
            ],
            options={
                'unique_together': {('nomi', 'tuzilma')},
            },
        ),
        migrations.CreateModel(
            name='HujjatShabloni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(choices=[('bildirgi', 'Bildirgi'), ('ariza', 'Ariza'), ('tushuntirish_xati', 'Tushuntirish xati'), ('hisobot', 'Hisobot'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='shablonlar/', verbose_name='Shablon fayli (Word)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tuzilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shablonlar', to='ppr.tarkibiytuzilma', verbose_name='Tarkibiy Tuzilma')),
                ('yuklovchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuklangan_shablonlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat Shabloni',
                'verbose_name_plural': 'Hujjat Shablonlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_rahbar', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bolim_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppr.bolimcategory')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_notifications', to=settings.AUTH_USER_MODEL)),
                ('tarkibiy_tuzilma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppr.tarkibiytuzilma')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PPRBajarildiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ppr_bajarildi_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PPRTasdiqlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPRYillikBajarildi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy', models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentyabr', 'Sentyabr'), ('Oktyabr', 'Oktyabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ppr_yillik_bajarildi_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPRYillikBajarildiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ppr_yillik_bajarildi_images/')),
                ('bajarildi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ppr.ppryillikbajarildi')),
            ],
        ),
        migrations.CreateModel(
            name='PPRYillikJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('oylar', models.JSONField()),
                ('status', models.CharField(choices=[('jarayonda', 'Jarayonda'), ('yuborildi', 'Yuborildi'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi'), ('bajarildi', 'Bajarildi')], default='jarayonda', max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('bekat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bekat')),
            ],
        ),
        migrations.CreateModel(
            name='PPRYillikTasdiqlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPRYillikYuborish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bolim_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.bolimcategory')),
                ('tarkibiy_tuzilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.tarkibiytuzilma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPRYuborish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('oy', models.IntegerField()),
                ('status', models.CharField(choices=[('yuborildi', 'Yuborildi'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='yuborildi', max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bolim_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.bolimcategory')),
                ('tarkibiy_tuzilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.tarkibiytuzilma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.RenameField(
            model_name='pprjadval',
            old_name='boshlash_sanasi',
            new_name='sana',
        ),
        migrations.RemoveField(
            model_name='bolim',
            name='bolim_nomi',
        ),
        migrations.RemoveField(
            model_name='pprbajarildi',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='pprbajarildi',
            name='images',
        ),
        migrations.RemoveField(
            model_name='pprjadval',
            name='obyekt',
        ),
        migrations.RemoveField(
            model_name='pprjadval',
            name='oy',
        ),
        migrations.RemoveField(
            model_name='pprjadval',
            name='yakunlash_sanasi',
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='extra_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='muddati_otgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obyektnomi',
            name='bekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bekat'),
        ),
        migrations.AddField(
            model_name='obyektnomi',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bolim'),
        ),
        migrations.AddField(
            model_name='obyektnomi',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obyektnomi',
            name='tarkibiy_tuzilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.tarkibiytuzilma'),
        ),
        migrations.AddField(
            model_name='pprbajarildi',
            name='bajarilgan_obyektlar',
            field=models.ManyToManyField(to='ppr.obyektnomi'),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='bekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bekat'),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bolim'),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='muddat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='obyektlar',
            field=models.ManyToManyField(related_name='ppr_jadvallari', to='ppr.obyektnomi'),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('yuborildi', 'Yuborildi'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi'), ('bajarildi', 'Bajarildi')], default='jarayonda', max_length=15),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='tarkibiy_tuzilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.tarkibiytuzilma'),
        ),
        migrations.AddField(
            model_name='pprturi',
            name='bekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bekat'),
        ),
        migrations.AddField(
            model_name='pprturi',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bolim'),
        ),
        migrations.AddField(
            model_name='pprturi',
            name='tarkibiy_tuzilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.tarkibiytuzilma'),
        ),
        migrations.AlterField(
            model_name='pprbajarildi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pprbajarildi',
            name='jadval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajarildilar', to='ppr.pprjadval'),
        ),
        migrations.AlterField(
            model_name='pprturi',
            name='davriyligi',
            field=models.IntegerField(blank=True, help_text='Masalan: qancha vaqtda', null=True),
        ),
        migrations.AddField(
            model_name='bolim',
            name='bolim_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodimlar', to='ppr.bolimcategory', verbose_name="Bo'lim nomi"),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='bolim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppr_jadvallari', to='ppr.bolimcategory'),
        ),
        migrations.AddField(
            model_name='pprbajarildiimage',
            name='bajarildi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ppr.pprbajarildi'),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.bolim'),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='bolim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yillik_jadvallar', to='ppr.bolimcategory'),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='obyekt',
            field=models.ManyToManyField(related_name='yillik_jadvallar', to='ppr.obyektnomi'),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='ppr_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.pprturi'),
        ),
        migrations.AddField(
            model_name='ppryillikjadval',
            name='tarkibiy_tuzilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppr.tarkibiytuzilma'),
        ),
        migrations.AddField(
            model_name='ppryillikbajarildi',
            name='jadval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajarildilar', to='ppr.ppryillikjadval'),
        ),
        migrations.AddField(
            model_name='ppryilliktasdiqlash',
            name='yuborish_paketi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qaror', to='ppr.ppryillikyuborish'),
        ),
        migrations.AddField(
            model_name='pprtasdiqlash',
            name='yuborish_paketi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qaror', to='ppr.ppryuborish'),
        ),
        migrations.AlterUniqueTogether(
            name='ppryillikbajarildi',
            unique_together={('jadval', 'oy', 'user')},
        ),
        migrations.AddConstraint(
            model_name='ppryuborish',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('yil', 'oy', 'bolim_category', 'tarkibiy_tuzilma'), name='unique_active_ppr_yuborish'),
        ),
    ]
