# Generated by Django 5.2.8 on 2025-12-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('monitoring', 'Monitoring'), ('tarkibiy', 'Tarkibiy Tuzilma Rahbari'), ('bekat', 'Bekat Rahbari'), ('bolim', "Bo'lim Boshlig'i")], max_length=20),
        ),
    ]
