# Generated by Django 5.2.8 on 2026-02-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0002_bolimcategory_hujjatshabloni_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
