# Generated by Django 5.2.8 on 2025-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0002_tuzilmanomi_bekat_birth_date_bekat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkibiytuzilma',
            name='tuzilma_nomi',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='TuzilmaNomi',
        ),
    ]
