# Generated by Django 5.2.8 on 2026-03-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0003_remove_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_times',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
