# Generated by Django 5.2.8 on 2025-12-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0003_alter_tarkibiytuzilma_tuzilma_nomi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaYuborishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='ariza_rasmlar_multi/')),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='ppr.arizayuborish')),
            ],
        ),
        migrations.CreateModel(
            name='KelganArizalarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='kelgan_rasmlar_multi/')),
                ('kelgan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='ppr.kelganarizalar')),
            ],
        ),
    ]
