# Generated by Django 5.2.8 on 2025-12-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ppr', '0004_arizayuborishimage_kelganarizalarimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arizayuborish',
            name='kim_tomonidan',
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='kim_tomonidan_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='kim_tomonidan_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
