# Generated by Django 5.2.8 on 2026-03-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0004_notification_read_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyektnomi',
            name='obyekt_nomi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
