# Generated by Django 5.2.8 on 2026-03-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0004_notification_read_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyektnomi',
            name='bolim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obyektlar', to='ppr.bolimcategory'),
        ),
        migrations.AddConstraint(
            model_name='obyektnomi',
            constraint=models.UniqueConstraint(fields=('obyekt_nomi', 'tarkibiy_tuzilma', 'bekat', 'bolim_category'), name='unique_obyekt_per_category'),
        ),
    ]
