# Generated by Django 5.2.8 on 2026-01-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0004_monitoring_customuser_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='user',
        ),
    ]
