# Generated by Django 5.2.8 on 2026-03-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0005_obyektnomi_bolim_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizayuborish',
            name='bolim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arizalar', to='ppr.bolimcategory'),
        ),
    ]
