# Generated by Django 5.2.8 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0005_remove_monitoring_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPRBajarildi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ppr_bajarildi_files/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ppr_bajarildi_images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('jadval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajarildi', to='ppr.pprjadval')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
