# Generated by Django 5.2.8 on 2025-12-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0005_remove_arizayuborish_kim_tomonidan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arizayuborish',
            name='kim_tomonidan_content_type',
        ),
        migrations.RemoveField(
            model_name='arizayuborish',
            name='kim_tomonidan_object_id',
        ),
        migrations.AddField(
            model_name='arizayuborish',
            name='kim_tomonidan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ariza_kim', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan'),
        ),
    ]
