# Generated by Django 5.2.8 on 2026-03-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0006_arizayuborish_bolim_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arizayuborish',
            name='bolim_category',
        ),
    ]
