# Generated by Django 5.2.8 on 2025-12-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0006_remove_arizayuborish_kim_tomonidan_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arizayuborish',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='kelganarizalar',
            name='rasm',
        ),
    ]
