# Generated by Django 5.2.8 on 2026-03-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0007_remove_arizayuborish_bolim_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppryillikbajarildiimage',
            name='bajarildi',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='bekat',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='bolim_category',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='obyekt',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='ppr_turi',
        ),
        migrations.RemoveField(
            model_name='ppryillikjadval',
            name='tarkibiy_tuzilma',
        ),
        migrations.RemoveField(
            model_name='ppryilliktasdiqlash',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ppryilliktasdiqlash',
            name='yuborish_paketi',
        ),
        migrations.RemoveField(
            model_name='ppryillikyuborish',
            name='bolim_category',
        ),
        migrations.RemoveField(
            model_name='ppryillikyuborish',
            name='tarkibiy_tuzilma',
        ),
        migrations.RemoveField(
            model_name='ppryillikyuborish',
            name='user',
        ),
        migrations.DeleteModel(
            name='PPRYillikBajarildi',
        ),
        migrations.DeleteModel(
            name='PPRYillikBajarildiImage',
        ),
        migrations.DeleteModel(
            name='PPRYillikJadval',
        ),
        migrations.DeleteModel(
            name='PPRYillikTasdiqlash',
        ),
        migrations.DeleteModel(
            name='PPRYillikYuborish',
        ),
    ]
