# Generated by Django 5.2.8 on 2025-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0007_remove_arizayuborish_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizayuborish',
            name='bildirgi',
            field=models.FileField(blank=True, null=True, upload_to='ariza_bildirgilar/'),
        ),
        migrations.AlterField(
            model_name='arizayuborish',
            name='status',
            field=models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi'), ('qabul qilindi', 'Qabul qilindi'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20),
        ),
    ]
