# Generated by Django 5.2.8 on 2025-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0008_arizayuborish_bildirgi_alter_arizayuborish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizayuborish',
            name='qayta_yuklandi',
            field=models.BooleanField(default=False),
        ),
    ]
