# Generated by Django 5.2.8 on 2025-12-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0009_arizayuborish_qayta_yuklandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprturi',
            name='davriyligi',
            field=models.CharField(blank=True, help_text='Masalan: har 1 oyda', max_length=100, null=True),
        ),
    ]
