# Generated by Django 5.2.8 on 2025-12-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0011_alter_pprturi_davriyligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pprturi',
            name='davriyligi',
            field=models.IntegerField(blank=True, help_text='Masalan: har necha oyda', max_length=100, null=True),
        ),
    ]
