# Generated by Django 5.2.8 on 2025-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0012_alter_pprturi_davriyligi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprjadval',
            name='kim_tomonidan',
            field=models.CharField(blank=True, choices=[('Texnik', 'Texnik'), ('AKT_xodimi', 'AKT_xodimi')], max_length=255, null=True),
        ),
    ]
