# Generated by Django 5.2.8 on 2025-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0013_pprjadval_kim_tomonidan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelganarizalar',
            name='ilovalar',
            field=models.FileField(blank=True, null=True, upload_to='ilovalar/'),
        ),
        migrations.DeleteModel(
            name='KelganArizalarImage',
        ),
    ]
