# Generated by Django 5.2.8 on 2025-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0014_kelganarizalar_ilovalar_delete_kelganarizalarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelganarizalar',
            name='akt_file',
            field=models.FileField(blank=True, null=True, upload_to='kelgan_fayllar/'),
        ),
    ]
