# Generated by Django 5.2.8 on 2025-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0015_alter_kelganarizalar_akt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bekat',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='bekat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bekat',
            name='passport_seriya',
        ),
        migrations.RemoveField(
            model_name='bekat',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tarkibiytuzilma',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='tarkibiytuzilma',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tarkibiytuzilma',
            name='passport_seriya',
        ),
        migrations.RemoveField(
            model_name='tarkibiytuzilma',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_seriya',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
