# Generated by Django 5.2.8 on 2025-12-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0018_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelganarizalar',
            name='status',
            field=models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20),
        ),
    ]
