# Generated by Django 5.2.8 on 2025-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0019_alter_kelganarizalar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprturi',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pprturi',
            name='kimlar_qiladi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pprturi',
            name='qisqachanomi',
            field=models.CharField(blank=True, help_text='Masalan: PPR1', max_length=100, null=True),
        ),
    ]
