# Generated by Django 5.2.8 on 2025-12-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0020_pprturi_comment_pprturi_kimlar_qiladi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprturi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
