# Generated by Django 5.2.8 on 2025-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0021_pprturi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprturi',
            name='vaqti',
            field=models.CharField(blank=True, choices=[('soat', 'Soat'), ('kun', 'Kun'), ('oy', 'Oy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pprturi',
            name='nomi',
            field=models.CharField(blank=True, choices=[('PPR1', 'PPR1'), ('PPR2', 'PPR2'), ('PPR3', 'PPR3')], max_length=100, null=True),
        ),
    ]
