# Generated by Django 5.2.8 on 2025-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0022_pprturi_vaqti_alter_pprturi_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pprturi',
            name='davriyligi',
            field=models.IntegerField(blank=True, help_text='Masalan: qancha vaqtda', max_length=100, null=True),
        ),
    ]
