# Generated by Django 5.2.8 on 2025-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0023_alter_pprturi_davriyligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pprturi',
            name='nomi',
            field=models.CharField(blank=True, help_text='Masalan: Nomi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pprturi',
            name='qisqachanomi',
            field=models.CharField(blank=True, choices=[('PPR1', 'PPR1'), ('PPR2', 'PPR2'), ('PPR3', 'PPR3')], max_length=100, null=True),
        ),
    ]
