# Generated by Django 5.2.8 on 2025-12-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0024_alter_pprturi_nomi_alter_pprturi_qisqachanomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pprturi',
            name='vaqti',
        ),
        migrations.AddField(
            model_name='pprturi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ppr_turlari/'),
        ),
        migrations.AlterField(
            model_name='pprturi',
            name='davriyligi',
            field=models.CharField(blank=True, help_text='Masalan: qancha vaqtda', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pprturi',
            name='qisqachanomi',
            field=models.CharField(blank=True, help_text='Masalan: Qisqa nomi', max_length=100, null=True),
        ),
    ]
