# Generated by Django 5.2.8 on 2025-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0025_remove_pprturi_vaqti_pprturi_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprjadval',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pprjadval',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
    ]
